enhancement:
    - '/add/i'
element request:
    - '/add element/i'
bug:
    - '/useless/i'
    - "/doesn't work/i"
    - "/not working/i"
    - "/error/i"
    - "/bug/i"
online interpreter:
    - "/online interpreter/i"
